name: Code Format Check

on:
  push:
    branches:
      - master
  pull_request:


jobs:
  black:
    runs-on: ubuntu-latest
    name: Black
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Black
        uses: psf/black@22.3.0  # already includes args "--check --diff"
  flake8:
    runs-on: ubuntu-latest
    name: Flake8
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade wheel pip
          pip install .[lint]
      - name: Lint examples
        run: flake8 examples --show-source
      - name: Lint scripts
        run: flake8 setup.py docs/conf.py scripts --show-source
      - name: Lint tests
        run: flake8 tests --show-source
      - name: Lint moviepy
        run: flake8 moviepy --show-source
  isort:
    runs-on: ubuntu-latest
    name: isort
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort
      - name: Check imports
        run: isort --check-only moviepy tests examples docs/conf.py scripts
